### DISCUSSION TITLE
Gremlin Console Issue

### DISCUSSION THREAD

**Discussion by atul161** [JanusGraph/janusgraph#3053] [Q&A]
Hi ,

I have a docker compose file setup.
After opening shell of janus graph server when i go to gremlin console and try to 
define schema then error occurs.
I have cassandra connected as a backend which is protected by id and password.
Any Help will be appreciated.

```
graph = JanusGraphFactory.open("conf/janusgraph-cql-server.properties")

```
gives error and even i am not able to print schema.

```
14:42:15 WARN  com.datastax.oss.driver.internal.core.control.ControlConnection  - [JanusGraph Session] Authentication error (AuthenticationException: Authentication error on node cassandra/172.26.0.4:9042: Node cassandra/172.26.0.4:9042 requires authentication (org.apache.cassandra.auth.PasswordAuthenticator), but no authenticator configured)
14:42:15 WARN  com.datastax.oss.driver.internal.core.control.ControlConnection  - [JanusGraph Session] Authentication errors encountered on all contact points. Please check your authentication configuration.
Could not instantiate implementation: org.janusgraph.diskstorage.cql.CQLStoreManager
Type ':help' or ':h' for help.

```
```
 version: "3.8"

services:
  # Janus Graph Server
  janusgraph:
    image: docker.io/janusgraph/janusgraph:latest
    container_name: jce-janusgraph
    environment:
      JANUS_PROPS_TEMPLATE: cql-es
      REST_TIMEOUT: 10000
      janusgraph.storage.hostname: jce-cassandra
      janusgraph.storage.username: cassandra
      janusgraph.storage.password: cassandra
      janusgraph.index.search.backend: elasticsearch
      janusgraph.index.search.hostname: jce-elastic
    ports:
      - "8182:8182"
    depends_on:
      - cassandra
      - elasticsearch
    networks:
      - jce-network
    healthcheck:
      test: [ "CMD", "bin/gremlin.sh", "-e", "scripts/remote-connect.groovy" ]
      interval: 10s
      timeout: 30s
      retries: 3


  cassandra:
    image: docker.io/bitnami/cassandra:4.0
    container_name: jce-cassandra
    ports:
      - '9042:9042'
      - '7000:7000'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
    volumes:
      - cassandra_data:/bitnami
    networks:
      - jce-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: jce-elastic
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "network.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "cluster.name=docker-cluster"
      - "xpack.security.enabled=false"
      - "discovery.zen.minimum_master_nodes=1"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - jce-network


networks:
  jce-network:
volumes:
  janusgraph-default-data:
  cassandra_data:
  elasticsearch_data:
```
