### ISSUE TITLE
Create and Access Traversal from client (other than gremlin console)

### ISSUE THREAD

**Issue by gblot** [JanusGraph/janusgraph#1299]
Hi everyone !

I'm encountering 2 issues while I am working on a client application based on a janus instance. The server is runing and looks good.

1. Is there a way to create the graph and the traversal remotely using a language like javascript (gremlin Node JS module) or Python ? These languages don't seem to include "create" methods. I would like to persistently create graphs  remotely from a client. Do you have some clues ?

2. I can't access an existing traversal from a client (except from the gremlin console). For example I have a graph called _graph1_, which is automatically binded to a traversal called _graph1_traversal_ (automatically binded for dynamic graphs), but when I try to manipulate this traversal, I get this message : **The traversal source [graph1_traversal] for alias [g] is not configured on the server. Here are some traces from my jupyter console** : 

<img width="833" alt="issue1" src="https://user-images.githubusercontent.com/8955608/47138252-28cb6080-d2b9-11e8-9dfa-bda3c9a2b423.png">

<img width="705" alt="issue2" src="https://user-images.githubusercontent.com/8955608/47138253-28cb6080-d2b9-11e8-8911-0d3c8b6b896d.png">

PS : Please don't be mad at me if my post is trivial, I am discovering janus with this project ...

THX

Guillaume

**Comment by pluradj** [comment]
Are you using JanusGraph 0.3.1? There were some [fixes](https://github.com/JanusGraph/janusgraph/issues/1200) in that release around dynamic binding of traversal sources.

**Comment by gblot** [comment]
Our current version is 0.3.0. I have requested an upgrade this morning. I'll give you some updates as soon as I could try it.

THX Jason :)

**Comment by gblot** [comment]
Hi, the version has been upgraded to 0.3.1 and my traversal is now accessible from my gremlin-python client. So, my point 2 is now fixed thanks to this upgrade. And thanks to you as well :)

But I'm keeping this post open because i am still searching solution for the point 1, regarding the remote creation of a graph. What I need to do here, is creating the graph and the traversal binding from gremlin-python. I am not sure if that is possible...

**Comment by rodrimc** [comment]
@gblot I'm not sure whether this is the "right" way to do it, but I managed to remotely create a graph using the following `js` code:

```
'use strict';

const gremlin = require ('gremlin');

const url = 'ws://localhost:8182/gremlin';
const Client  = gremlin.driver.Client;
const client = new Client (url, 'g');

async function f ()
{
  try
  {
    let data = await client.submit ('ConfiguredGraphFactory.create("mycustomgraph"); 0');
    console.log (data);
  }
  catch (err)
  {
    console.log (err);
  }
}
f ();
```

Perhaps the Janus folks could give us some clues if this is the best approach.

**Comment by aofengli** [comment]
If you have configured a dynamic graph。
You can refer to the following configuration：
```yaml
host: 0.0.0.0
port: 8182
scriptEvaluationTimeout: 180000
channelizer: org.janusgraph.channelizers.JanusGraphWebSocketChannelizer
graphManager: org.janusgraph.graphdb.management.JanusGraphManager
graphs: {
  # ConfigurationManagementGraph: conf/janusgraph-cql-configurationgraph.properties
  ConfigurationManagementGraph: conf/janusgraph-hbase-es-server.properties
}
scriptEngines: {
  gremlin-groovy: {
    plugins: { org.janusgraph.graphdb.tinkerpop.plugin.JanusGraphGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin: {classImports: [java.lang.Math], methodImports: [java.lang.Math#*]},
               org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {files: [scripts/init.groovy]}}}}
serializers:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { serializeResultToString: true }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV2d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  # Older serialization versions for backwards compatibility:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoLiteMessageSerializerV1d0, config: {ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { serializeResultToString: true }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV2d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistryV1d0] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistryV1d0] }}
processors:
  - { className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor, config: { sessionTimeout: 28800000 }}
  - { className: org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor, config: { cacheExpirationTime: 600000, cacheMaxSize: 1000 }}
metrics: {
  consoleReporter: {enabled: true, interval: 180000},
  csvReporter: {enabled: true, interval: 180000, fileName: /tmp/gremlin-server-metrics.csv},
  jmxReporter: {enabled: true},
  slf4jReporter: {enabled: true, interval: 180000},
  gangliaReporter: {enabled: false, interval: 180000, addressingMode: MULTICAST},
  graphiteReporter: {enabled: false, interval: 180000}}
maxInitialLineLength: 4096
maxHeaderSize: 8192
maxChunkSize: 8192
maxContentLength: 65536
maxAccumulationBufferComponents: 1024
resultIterationBatchSize: 64
writeBufferLowWaterMark: 32768
writeBufferHighWaterMark: 65536
```
mark `org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {files: [scripts/init.groovy]}}}}`

the `scripts/init.groovy` is : 
```shell
def globals = [:]


def getGraph() {
    def graphNames =  ConfiguredGraphFactory.getGraphNames();
    def graphMaps = [:];
    for (graphName in graphNames) {
        def g = ConfiguredGraphFactory.open(graphName);
        graphMaps.put(graphName, g.traversal())
    }
    return graphMaps;
}

globals << getGraph()
```
