### ISSUE TITLE
add a key named "ConfigurationManagementGraph" to the "graphs" property

### ISSUE THREAD

**Issue by lmcrazy** [JanusGraph/janusgraph#1322]
Please help to have a look, thanks!
I've configured ConfigurationManagementGraph！But it still reported an error。
config:
![image](https://user-images.githubusercontent.com/9508140/48998248-e9344600-f18d-11e8-9f33-f3ef32c3266d.png)
![image](https://user-images.githubusercontent.com/9508140/48998329-1d0f6b80-f18e-11e8-8cfa-7666f718417b.png)

my code is:
`
 @Test
    public void graphConfigurationShouldBeWhatWeExpectWhenUsingTemplateConfiguration()
        throws Exception {

        try {

            JanusGraphManager gm;
            Settings set =new Settings();
            set.host="172.16.161.115";
            gm = new JanusGraphManager(set);
            final Map<String, Object> map = new HashMap<>();
            map.put(STORAGE_BACKEND.toStringWithoutRoot(), "hbase");
            map.put("storage.hostname", "172.16.161.115");
            //ConfiguredGraphFactory.createTemplateConfiguration(new MapConfiguration(map));
            ConfigurationManagementGraph instance = ConfigurationManagementGraph.getInstance();
            final StandardJanusGraph graph = (StandardJanusGraph) ConfiguredGraphFactory.create("ghlml");
            final StandardJanusGraph graph1 = (StandardJanusGraph) ConfiguredGraphFactory.open("ghlml");
            instance.createTemplateConfiguration(new MapConfiguration(map));
            Set<String> graphNames = ConfiguredGraphFactory.getGraphNames();
            for(String str:graphNames){
            	System.out.println("---"+str);
            }
            assertNotNull(graph);
            assertEquals(graph, graph1);
            
            assertEquals("ghlml", graph.getConfiguration().getConfiguration().get(GRAPH_NAME));
           // assertEquals("inmemory", graph.getConfiguration().getConfiguration().get(STORAGE_BACKEND));

        } finally {
            //ConfiguredGraphFactory.removeConfiguration("graph1");
            //ConfiguredGraphFactory.close("graph1");
        }
    }
`

error code:
`
org.janusgraph.graphdb.management.utils.ConfigurationManagementGraphNotEnabledException: Please add a key named "ConfigurationManagementGraph" to the "graphs" property in your YAML file and restart the server to be able to use the functionality of the ConfigurationManagementGraph class.
	at org.janusgraph.graphdb.management.ConfigurationManagementGraph.getInstance(ConfigurationManagementGraph.java:97)
	at pluradj.janusgraph.example.ConfiguredGraphFactoryTest.graphConfigurationShouldBeWhatWeExpectWhenUsingTemplateConfiguration(ConfiguredGraphFactoryTest.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

java.lang.RuntimeException: org.janusgraph.graphdb.management.utils.ConfigurationManagementGraphNotEnabledException: Please add a key named "ConfigurationManagementGraph" to the "graphs" property in your YAML file and restart the server to be able to use the functionality of the ConfigurationManagementGraph class.
	at org.janusgraph.core.ConfiguredGraphFactory.getConfigGraphManagementInstance(ConfiguredGraphFactory.java:169)
	at org.janusgraph.core.ConfiguredGraphFactory.removeTemplateConfiguration(ConfiguredGraphFactory.java:258)
	at pluradj.janusgraph.example.ConfiguredGraphFactoryTest.cleanUp(ConfiguredGraphFactoryTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.janusgraph.graphdb.management.utils.ConfigurationManagementGraphNotEnabledException: Please add a key named "ConfigurationManagementGraph" to the "graphs" property in your YAML file and restart the server to be able to use the functionality of the ConfigurationManagementGraph class.
	at org.janusgraph.graphdb.management.ConfigurationManagementGraph.getInstance(ConfigurationManagementGraph.java:97)
	at org.janusgraph.core.ConfiguredGraphFactory.getConfigGraphManagementInstance(ConfiguredGraphFactory.java:167)
	... 27 more

`

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.

**Comment by VINAYAK179** [comment]
I do have the same problem, Can you give the solution

**Comment by EthanPhan** [comment]
I have the same problem with JanusGraph 0.4.0, can anyone give a solution for this?

**Comment by jsndh-pm** [comment]
> I have the same problem with JanusGraph 0.4.0, can anyone give a solution for this?

Did you find any solution ? :(  I have the same issue with 0.4.1

**Comment by roamerop** [comment]
same issue on version 0.6.1

**Comment by jerlendds** [comment]
I'm also running into this issue, currently running through the `janusgraph/janusgraph:1.0.0-rc2` and most lately through cloning the git repo and building from that. Ive modified and mounted hardcoded config options with the correct values because I've been losing my mind trying to debug this for the past two days. Is there any interest from the JanusGraph team to look into this? I can push a repo where the problem can be reproduced but I'd like to know if I have to switch away from JanusGraph if this can't be fixed. Being able to create and access dynamic graphs is something that's a requirement for my app

```yaml
  janus:
    build:
      context: ./janus/1.0/
      dockerfile: ./Dockerfile
    ports:
      - "8182:8182"
    environment:
      janusgraph.set-vertex-id: true
      storage.backend: cql
      storage.hostname: sdb:9042
      janusgraph.index.search.backend: elasticsearch
      janusgraph.index.search.hostname: index:${ELASTIC_PORT-.env ELASTIC_PORT needs to be set}
    volumes:
      - "./janus/config/janusgraph.properties:/etc/opt/janusgraph/janusgraph.properties:ro"
      - "./janus/config/janusgraph-server.yaml:/etc/opt/janusgraph/janusgraph-server.yaml:ro"
      - "./janus/config/janusgraph-server.yaml:/opt/janusgraph/conf/remote-objects.yaml:ro"
      - "./janus/config/empty-sample.groovy:/opt/janusgraph/scripts/empty-sample.groovy:ro"
```

_janusgraph-server.yaml_

```yml

host: [0.0.0.0]
port: 8182
evaluationTimeout: 30000
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
graphManager: org.janusgraph.graphdb.management.JanusGraphManager
graphs: {
  ConfigurationManagementGraph: /etc/opt/janusgraph/janusgraph.properties,
}
scriptEngines: {
  gremlin-groovy: {
    plugins: { org.janusgraph.graphdb.tinkerpop.plugin.JanusGraphGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin: {classImports: [java.lang.Math], methodImports: [java.lang.Math#*]},
               org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {files: []}}}}
processors:
  - { className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor, config: { sessionTimeout: 28800000 }}
  - { className: org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor, config: { cacheExpirationTime: 600000, cacheMaxSize: 1000 }}
metrics: {
  consoleReporter: {enabled: true, interval: 180000},
  csvReporter: {enabled: true, interval: 180000, fileName: /tmp/gremlin-server-metrics.csv},
  jmxReporter: {enabled: true},
  slf4jReporter: {enabled: true, interval: 180000},
  graphiteReporter: {enabled: false, interval: 180000}}
maxInitialLineLength: 4096
maxHeaderSize: 8192
maxChunkSize: 8192
maxContentLength: 65536
maxAccumulationBufferComponents: 1024
resultIterationBatchSize: 64
writeBufferLowWaterMark: 32768
writeBufferHighWaterMark: 65536
threadPoolWorker: 1
gremlinPool: 8

```

_janusgraph.properties_
