### ISSUE TITLE
Evaluation results of GitHub actions

### ISSUE THREAD

**Issue by farodin91** [JanusGraph/janusgraph#1987]
I tested github actions for a release build test.
Short facts for github actions: 20 concurrent jobs and 12h runtime per job

Major issues with Github Actions requires Github Teams for Open Source and allows only 20000min to build per month.

```yml
name: RELEASE BUILD

on:
  pull_request: {}
  push: { branches: [ master ] }

jobs:
  test-release-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: mvn clean install -Pjanusgraph-release -Dgpg.skip=true -DskipTests=true
    - run: sudo apt-get update && sudo apt-get install -y expect
    - run: mvn install -pl janusgraph-dist -Pjanusgraph-release -Dgpg.skip=true
```
