### ISSUE TITLE
Healthcheck endpoint for janusgraph

### ISSUE THREAD

**Issue by nbenaglia** [JanusGraph/janusgraph#2197]
Hi,
is there a way to check the health of a janusgraph service?

**Comment by li-boxuan** [comment]
Hi, you should consider posting in the [janusgraph-users ](https://groups.google.com/g/janusgraph-users)Google group as that one is more active. That being said, you may want to check out https://docs.janusgraph.org/advanced-topics/monitoring/.

**Comment by nbenaglia** [comment]
Here a snippet of a docker-compose I found for healthcheck:

```
  healthcheck:
      test: ["CMD", "bin/gremlin.sh", "-e", "scripts/remote-connect.groovy"]
      interval: 10s
      timeout: 30s
      retries: 3
```
