### ISSUE TITLE
Hadoop integration tests are failing for scylladb

### ISSUE THREAD

**Issue by li-boxuan** [JanusGraph/janusgraph#2505]
See https://github.com/JanusGraph/janusgraph/pull/2352#discussion_r587617149

The same tests pass for Cassandra but fail for Scylladb.

**Comment by porunov** [comment]
I confirm that locally running those tests are very slow when using Scylla and fast when using Cassandra.
I don't know the reason for this behavior but here are my observations:
- In [this blog post](https://docs.scylladb.com/stable/kb/scylla-and-spark-integration.html#scylla-limitations) they are talking about limitations and they said: `Scylla doesn’t populate system.size_estimates, and therefore the connector won’t be able to perform automatic split sizing optimally.`. Not sure if that affect tests or not but could be.
- The test which is running 7 minutes when Cassandra is used ([here](https://github.com/JanusGraph/janusgraph/actions/runs/4155096401/jobs/7187951184)) takes more than 3 hours to finish when ScyllaDB is used ([here](https://github.com/JanusGraph/janusgraph/actions/runs/4155096422/jobs/7187958366)).
- For Hadoop we are using Cassandra's [CqlInputFormat](https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/hadoop/cql3/CqlInputFormat.java) which is using datastax 3.x driver instead of datastax 4.x driver. I don't think that's a driver problem because it works fine with Cassandra, but something to know about just in case.

I also think it might make sense to warn users about using ScyllaDB with JanusGraph Hadoop integration. I don't know if Hadoop integration will be performing normally when used with ScyllaDB (at least I didn't test ScyllaDB performance for that integration myself).

cc @dorlaor

**Comment by dorlaor** [comment]
Hmm, does Scylla in this test use the same bindings as C*? It should work too.
It might be the docker setup of Scylla or it can be related to the size estimates
although this https://www.scylladb.com/2018/08/21/spark-scylla-2/ shows Scylla does
support it and we do have it in our docs. Could be that the estimate may not be accurate.

Is it possible to run in debug mode and figure out the differences?

**Comment by porunov** [comment]
> Hmm, does Scylla in this test use the same bindings as C*? It should work too. It might be the docker setup of Scylla or it can be related to the size estimates although this https://www.scylladb.com/2018/08/21/spark-scylla-2/ shows Scylla does support it and we do have it in our docs. Could be that the estimate may not be accurate.
> 
> Is it possible to run in debug mode and figure out the differences?

Yes the same bindings and the tests are identical.
The executed tests are located here: https://github.com/JanusGraph/janusgraph/tree/master/janusgraph-cql/src/test/java/org/janusgraph/hadoop

Here is a flow to execute tests with debug enabled:
1) Change debug level from `"info"` to `"debug"` here: https://github.com/JanusGraph/janusgraph/blob/759266ad469b94243ff419cd50e0832c8b800929/janusgraph-cql/src/test/resources/log4j2-test.xml#L11
2) Execute build `janusgraph-cql` with the next command: 
```
mvn clean install --projects janusgraph-cql -DskipTests=true --batch-mode --also-make
```
3) Start Hadoop tests with Cassandra:
```
mvn -X verify --projects janusgraph-cql -Pcassandra3-murmur -Dtest="/hadoop/*"
```
4) See debug logs here `janusgraph-cql/target/test.log`
5) Start Hadoop tests with ScyllaDB (will take much longer to finish):
```
mvn -X verify --projects janusgraph-cql -Pscylladb -Dtest="/hadoop/*"
janusgraph-cql/target/test.log
```
6) See debug logs here `janusgraph-cql/target/test.log`

----

It might really be misconfiguration of the ScyllaDB docker instance we use because we use Testcontainers's `CassandraContainer` to start the docker instance but we just simply provide `scylladb/scylla` docker image name instead of Cassandra's image name. 
Quickly checking I see it also applies environment variables related to JVM which I assume will be ignored in ScyllaDB.
Quckly checking I see we apply the next environment variables (I could miss some here):
```
withEnv("CASSANDRA_SNITCH", "GossipingPropertyFileSnitch");
withEnv("JVM_OPTS", "-Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.initial_token=0");
withEnv("HEAP_NEWSIZE", "128M");
withEnv("MAX_HEAP_SIZE", "1024M");
withEnv("CASSANDRA_ENDPOINT_SNITCH", "GossipingPropertyFileSnitch");
withEnv("CASSANDRA_DC", "datacenter1");
withEnv("MAX_HEAP_SIZE", "2G");
withEnv("HEAP_NEWSIZE", "1G");
```
We also attach the next parameters when starting cassandra (probably they will also be ignored in ScyllaDB as this is Java's style):
```
-Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.load_ring_state=false
```

cc @farodin91

**Comment by kbr-scylla** [comment]
> -Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.load_ring_state=false

`load_ring_state=false`...
Won't this turn the Cassandra cluster into a set of single-node clusters or something? It's not a safe option, it makes the node lose important metadata on restart. TBH I have no idea what will happen and whether it affects restarts only or more.

(offtop, but why does this option even exist? I wouldn't expect it to do anything different than completely break everything. I mean the cluster might run, but whatever it does - it won't make any sense)

Anyway you should probably try without this option first (and also without skip_wait_for_gossip_to_settle, which might also lead to incorrect cluster setup).
Maybe ``load_ring_state=false` doesn't matter if nodes aren't restarted during the test... are they? But then, if not, why would the option be used in the first place?

Does the measurement include bootstrap times? Does it even bootstrap the clusters correctly (sequentially)? If it's using unsafe options like `load_ring_state=false` then I'd expect anything to happen.

> For ScyllaDB container we place the next configuration to the same location /etc/cassandra/cassandra.yaml: 

All of the options that you provided, and also this file I think, will be ignored. According to the docs (e.g. https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/create-cluster) Scylla loads its config from `/etc/scylla/scylla.yaml`. The config should probably also be adjusted for Scylla. Best would be to take some default config from Scylla container/installation and adjust it appropriately so the parameters important for you match the ones from Cassandra config.

**Comment by fruch** [comment]
@porunov 
passing down of those parameters is done in scylla docker image via environment variables but via command line arguments

something like this:
```
docker run  scylladb/scylla --smp 1 --skip-wait-for-gossip-to-settle 1
```
 
`load_ring_state` doesn't have equivalent in scylla

**Comment by fruch** [comment]
just adding to @kbr-scylla comments, 
if one node is used in the test `skip_wait_for_gossip_to_settle` is safe enough to be used (we are doing so in scylla tests quite a lot)

**Comment by porunov** [comment]
Thank you @kbr-scylla and @fruch for your input!

I will update the test container to use those parameters instead of environment variables.
We use only a single node for ScyllaDB tests as for now. So, I guess it should be fine as well.

Not sure about why `load_ring_state` was used at the first place, but I think it shouldn't harm the tests because we really don't need previous container state. This container used for tests only. We don't ship it anywhere else.
 
As for ScyllaDB configuration I also noticed that there was a bug in the Testcontainer configuration and ScyllaDB configs were not applied properly. I fixed the container to apply both Cassandra and ScyllaDB configs as part of the PR which adds ScyllaDB driver into JanusGraph #3578 (currently under review).
Nevertheless in that PR I tested [Hadoop tests](https://github.com/JanusGraph/janusgraph/issues/2505#issuecomment-1428257091) with correct ScyllaDB configuration and the performance was slow as well (3 hours instead of 7 minutes).

I will try using `--smp 1 --skip-wait-for-gossip-to-settle 0` and see if it helps with those tests.

**Comment by porunov** [comment]
I was able to fix the container to correctly apply ScyllaDB configuration as well as those parameters in #3578 . As a result the performance issue is gone for ScyllaDB and tests are executed normally.

That said, I'm currently struggling to fix tests where we start ScyllaDB with certificates.

The scylla.yaml file is like this:
```
cluster_name: 'Test Cluster'
num_tokens: 4
hinted_handoff_enabled: false
max_hint_window_in_ms: 10800000 # 3 hours
hinted_handoff_throttle_in_kb: 1024
max_hints_delivery_threads: 2
batchlog_replay_throttle_in_kb: 1024
authenticator: AllowAllAuthenticator
authorizer: AllowAllAuthorizer
role_manager: CassandraRoleManager
permissions_validity_in_ms: 2000
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
disk_failure_policy: stop
commit_failure_policy: stop
key_cache_size_in_mb:
key_cache_save_period: 14400
row_cache_size_in_mb: 0
row_cache_save_period: 0
counter_cache_size_in_mb:
counter_cache_save_period: 7200
saved_caches_directory: /var/lib/scylla/saved_caches
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
  - class_name: org.apache.cassandra.locator.SimpleSeedProvider
    parameters:
      - seeds: "127.0.0.1"
concurrent_reads: 32
concurrent_writes: 32
concurrent_counter_writes: 32
memtable_allocation_type: heap_buffers
index_summary_resize_interval_in_minutes: 60
trickle_fsync: false
trickle_fsync_interval_in_kb: 10240
storage_port: 7000
ssl_storage_port: 7001
listen_address: localhost
start_native_transport: true
native_transport_port: 9042
rpc_address: 0.0.0.0
rpc_keepalive: true
incremental_backups: false
snapshot_before_compaction: false
auto_snapshot: true
column_index_size_in_kb: 64
compaction_throughput_mb_per_sec: 16
sstable_preemptive_open_interval_in_mb: 50
read_request_timeout_in_ms: 5000
range_request_timeout_in_ms: 10000
write_request_timeout_in_ms: 2000
counter_write_request_timeout_in_ms: 5000
cas_contention_timeout_in_ms: 1000
truncate_request_timeout_in_ms: 60000
request_timeout_in_ms: 10000
cross_node_timeout: false
endpoint_snitch: SimpleSnitch
dynamic_snitch_update_interval_in_ms: 100
dynamic_snitch_reset_interval_in_ms: 600000
dynamic_snitch_badness_threshold: 0.1

server_encryption_options:
  internode_encryption: none
  keystore: conf/.keystore
  keystore_password: cassandra
  truststore: conf/.truststore
  truststore_password: cassandra
client_encryption_options:
  enabled: true
  # If enabled and optional is set to true encrypted and unencrypted connections are handled.
  optional: false
  keystore: /etc/ssl/node.keystore
  keystore_password: cassandra
  certificate: /etc/ssl/node.crt
  keyfile: /etc/ssl/node.key

internode_compression: dc
inter_dc_tcp_nodelay: false
enable_user_defined_functions: false
tombstone_warn_threshold: 1000
tombstone_failure_threshold: 100000
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
compaction_large_partition_warning_threshold_mb: 100
``` 

The output log file is available here: https://gist.github.com/porunov/1ad5e396d815df0b220f69ea6b7d5177

The error received:
```
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 196, in <module>
    args.func(args)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 122, in check_version
    current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 80, in get_api
    return get_json_from_url("http://" + api_address + path)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 75, in get_json_from_url
    raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
RuntimeError: Failed to get "http://localhost:10000/storage_service/scylla_release_version" due to the following error: <urlopen error [Errno 99] Cannot assign requested address>
```

Certificates used: https://github.com/porunov/janusgraph/tree/feature/scylla-storage-backend/janusgraph-cql/src/test/resources/cert

Notice, I retrieved `node.key` file from the keystore using `cassandra` keystore password via the next command (not sure if that could lead to startup error):
```
openssl pkcs12 -in node.keystore -nodes -nocerts -out node.key
```

Locally these tests can be started using the next commands:
```
mvn clean install --projects janusgraph-scylla -DskipTests=true --batch-mode --also-make
mvn verify --projects janusgraph-scylla -Pscylla-murmur-ssl -Dtest="**/diskstorage/cql/CQLStoreTest.java"
```

The second command will produce log file of the test including ScyllaDB server logs `janusgraph-scylla/target/test.log`;

The strange thing is that the container starts normally if we disable encryption (i.e. `client_encryption_options.enabled: false`). With encryption enabled it fails to start, but doesn't provide any error relating to encryption or certificate problems.
