### ISSUE TITLE
Missing required Elasticsearch permissions documentation

### ISSUE THREAD

**Issue by petergvizd-s1** [JanusGraph/janusgraph#3999]
**Describe the feature:**
Currently I was not able to find permissions, that Janusgraph require to be able to successfully work with Elasticsearch. Would it be possible to add this section to documentation?
[Please add a description for your feature.]
I think it would be beneficial for all users of Janusgraph to grant at least privilege to Elasticsearch user.
**Describe a specific use case for the feature:**
[If possible add a description of the specific use case.]

**Comment by michielboekhoff** [comment]
Not sure if this is applicable to your use-case, but I found that deploying The Hive (which uses Janusgraph) with this ES role worked:

```yaml
hive_elastic_role:
  cluster: [ "manage" ]
  indices:
  - names: [ "thehive*" ]
    privileges: [ "all" ]
```
